{% set name = "glpk" %}
{% set version = "4.65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4281e29b628864dfe48d393a7bedd781e5b475387c20d8b0158f329994721a10
  patches:
    # https://lists.nongnu.org/archive/html/bug-glpk/2018-03/msg00000.html
    # patch will be in next release
    - remove_unnecessary_warning.diff

build:
   number: 4
   run_exports:
     # changes SONAME at minor rev.
     - {{ pin_subpackage("glpk", max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make           # [unix]
    - libtool        # [unix]
  host:
    - gmp {{ gmp }}  # [unix]
  run:
    - gmp            # [unix]

test:
  requires:
    - {{ compiler('c') }}  # [unix]
    - python
    - pip
    - setuptools >=68      # [unix]
    - cython >=3.0         # [unix]
    - wheel                # [unix]
    - pytest               # [unix]
  files:
    - pyproject.toml       # [unix]
    - setup.py             # [unix]
    - spam.pyx             # [unix]
    - test_spam.py         # [unix]
    - test.c
    - plan.mps
    - test_ctypes.py
  commands:
    # ---------- Test glpsol executable ----------
    - $PREFIX/bin/glpsol --version                 # [unix]
    - $PREFIX/bin/glpsol --mps plan.mps            # [unix]
    - '%LIBRARY_BIN%\\glpsol.exe --version'        # [win]
    - '%LIBRARY_BIN%\\glpsol.exe --mps plan.mps'   # [win]

    # ---------- Linux/macOS: Build Cython-extension and run pytest ----------
    - echo "Editable install via pip (no build isolation) ..."        # [unix]
    - python -m pip install -e . --no-build-isolation                 # [unix]
    - echo "Run pytest ..."                                           # [unix]
    - pytest -vv test_spam.py                                         # [unix]

    # ---------- Linux/macOS: Checking shared and static GLPK libraries ----------
    - echo "Checking shared and static libraries in ${PREFIX}/lib ..."  # [unix]
    - test -f ${PREFIX}/lib/libglpk${SHLIB_EXT}   # [unix]
    - test -s ${PREFIX}/lib/libglpk${SHLIB_EXT}   # [unix]

    - echo "Checking exported symbols for glp_version ..."  # [unix]
    - nm -D ${PREFIX}/lib/libglpk.so | grep glp_version     # [linux]
    - nm -gU ${PREFIX}/lib/libglpk.dylib | grep glp_version # [osx]

    # ---------- Windows: check layout DLL ----------
    - echo "Check Windows layout (dll/lib) ..."                       # [win]
    - if not exist %LIBRARY_BIN%\\glpk.dll exit 1                     # [win]
    - if not exist %LIBRARY_BIN%\\glpk_%PKG_VERSION:.=_%.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\glpk.lib exit 1                     # [win]
    - if not exist %LIBRARY_LIB%\\glpk_static.lib exit 1              # [win]

    # ---------- Linux/macOS: Check ะก call GLPK lib ----------
    - echo "Check C call GLPK lib ..."                                # [unix]
    - export CFLAGS="${CFLAGS} -I${PREFIX}/include -L${PREFIX}/lib"   # [unix]
    - export LDFLAGS="${LDFLAGS} -Wl,-rpath,${PREFIX}/lib"            # [unix]
    - $CC $CFLAGS $LDFLAGS test.c -lglpk -o test.out                  # [unix]
    - ./test.out                                                      # [unix]

    # ---------- Test shared library using python ctypes module ----------
    - echo "python test_ctypes.py ..."
    - python test_ctypes.py

  # downstreams:
  #   - cvxopt
  #   - pulp


about:
  home: https://www.gnu.org/software/glpk
  license: GPL-3.0
  license_file: COPYING
  license_family: GPL
  summary: GNU Linear Programming Kit
  description: |
    The GLPK (GNU Linear Programming Kit) package is intended for solving
    large-scale linear programming (LP), mixed integer programming (MIP), and
    other related problems. It is a set of routines written in ANSI C and
    organized in the form of a callable library.
  dev_url: https://www.gnu.org/software/glpk
  doc_url: https://www.gnu.org/software/glpk/#TOCdocumentation

extra:
  recipe-maintainers:
    - jjhelmus
    - aebrahim
    - jakirkham
    - snorfalorpagus
