travis:
  secure:
    BINSTAR_TOKEN: bGEv/4J2vl9q/Cf5G1s35YjkshXRVa44FeeMa7HM5W9Zd4J7+BZhiFsx+ualm7Hw9xcTWQDY0mN9+DH6CUNWh/jiur0zUng9HKe6T3KJh4x5MZqjAE3HjHr6VhrU2Uxe96VbUuiTlEM8GOdI4Lj0pbw72ZdyyqKQ9b9NEwQSj3U53TZrawTu4EX9al+uToh1efkJtuz2272KtlYkaC4iRPc1YJgmS51OJseRGGeCr4vNJ3c8v6IqfDg6f2WSmFm/2RDNnBW2VCXfFiMPMkssyFEvjhlk3pdrA5dwphmbCCcpQoZPYWxdmxnr0/K9mkpLHe2004/cbC6ue7wB0vhltd9oGMm2b9e+jq0D8i/zLI2jCO0PhJxB6NEa/QeXVonXCQ0dqw8n8yPxBTzQeUsMhvY6j9gjDikk7cX2YWFS3ic6c8Uaja3zImOMT/aOchBDS9oz9c7OwIpJlpC5Pjhzlo1tbIW1OuV9i8pGMHQ/7PRCu5HD4+La7fYMs4PZHzrRyNoItE+Y0TzG063GFliEhXmaL5ou6nq9dMN2Bm9xVHWJl1eHbotjtZZj2JaSYqsjiWATWzWNGbwl5J71k9l0UOmHXXRjOpFvUk/JM6i8tYHkRf4lqzOAENBt6+ACm9lCuVntkxYdiw6bK2fbqI8yEJCEX6xlxtT/DkBuwYLanK0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
